name: "Download Simple Auth"
description: "Download Simple Auth bits from github release"
runs:
    using: "composite"
    steps:
      - name: Download Simple Auth bits
        shell: pwsh
        run: |
          ./.github/workflows/download-simpleauth/downloadWithRetry.ps1