name: azure login

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: login with token
        env:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          ./.github/workflows/scripts/login.sh