name: azure login

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login with token
        run: |
          bash login.sh ${{ secrets.AZURE_CREDENTIALS }}
        working-directory: ./.github/workflows/scripts