name: azure login

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'input the CD pipeline run ID to fetch the artifact'
        required: true
        default: ''

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install VSCE command
        run: |
          npm install vsce -g
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch
      - name: Download Artifacts from Previous Workflow
        uses: synergy-au/download-workflow-artifacts-action@v1
        with:
          # Optional, GITHUB_TOKEN is used by default. Token is needed for private repos.
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          # Optional, the ID of the workflow that triggered the run is used by default
          workflow-run-id: ${{ github.event.input.run_id }}
      - name: ls
        run : ls
      - name: Unzip artifact
        run: unzip release.zip
      # - name: unzip artifacts
      #   run: |
      #     unzip release.zip
      - name: echo json
        run: |
          ls