name: azure login

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'input the CD pipeline run ID to fetch the artifact'
        required: true
        default: ''

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install VSCE command
        run: |
          npm install vsce -g
      - name: Download release artifacts
        uses: Legit-Labs/action-download-artifact@v2
        with:
          run_id: ${{ github.event.input.run_id }}
          name: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: cd.yml
          path: .
      - name: unzip artifacts
        run: |
          unzip release.zip
      - name: echo json
        run: |
          ls 
          ls release