name: azure login

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login with token
        env:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          clientId=$(echo $creds | jq -r '.clientId')
          echo $clientId
          bash login.sh $creds
        working-directory: ./.github/workflows/scripts