name: azure pipeline

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
        echo "123123"