name: azure login

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: update json
        uses: restack/update-json-file-action@v1.1
        with:
          file: pacakges/beta/pacakge.json
          fields: "{'version': '1.2.4', 'aiKey': '1233425234653264'}"
      - name: echo json
        run: |
          echo pacakges/beta/pacakge.json