# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: echo aikey
        env: 
          aikey: ${{ secrets.AIKEY }}
        run: | 
          echo $aikey
      # Runs a single command using the runners shell
      - name: Update my-file.json description
        uses: jossef/action-set-json-field@v1
        with:
            file: ./package.json
            field: aiKey
            value: ${{ secrets.AIKEY }}
      - name: Setup git
        run: |
          git config --global user.name 'wenytang-ms-123'
          git config --global user.email 'wenytang@microsofr.com'

      - name: commit
        run: |
          git add .
          git commit -m "chore: update AI key"

      - name: echo
        run: |
          less package.json

  release:
    runs-on: ubuntu-latest
    environment: Production_ENV
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Test env vars for python
        run: echo $REPO_SECRET
        env:
          ENV_SECRET: ${{ secrets.PUBLISH_PAT }} 
          REPO_SECRET: ${{ secrets.AIKEY }} 