name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, rc or stable)"
        required: true
        default: "rc"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: set state
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}