name: "for test schedule"
run-name: this is a test name ${{github.event.inputs.preid}}
on:
  workflow_dispatch:
    inputs:
      preid:
        description: "this is a test"
        default: "rc"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "123"
      - name: sss
        if: ${{ github.event.inputs.preid }}
        run: |
          echo ${{ github.event.inputs.preid }}