name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, rc or stable)"
        required: true
        default: "rc"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: add tag
        run: |
          git tag 'v1.1.1'

      - name: Set the value
        run: |
          echo "action_state=$(git tag --points-at HEAD | grep v)" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.action_state }}" 