# This is a basic workflow to help you get started with Actions

name: BBBBB

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: add tag
      run: |
        git tag 'v1.1.1'

    - name: Set the value
      id: step_one
      run: |
        echo "action_state=$(git tag --points-at HEAD)" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" 